package handlers

import (
	"encoding/json"
	"net/http"
	"strings"
	"time"
	"zenvault-backend/auth"
	"zenvault-backend/db"
	"zenvault-backend/models"

	"golang.org/x/crypto/bcrypt"
)

func Register(w http.ResponseWriter, r *http.Request) { //function that accepts a request and give back a response

	var user models.User
	// Open the package the user sent, read the JSON inside it, translate it into my Go struct, and place the result inside my variable.
	err := json.NewDecoder(r.Body).Decode(&user)

	if err != nil {
		SendError(w, "invalid Request", http.StatusBadRequest)
		return
	}

	hashpassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), bcrypt.DefaultCost) // Hash my password

	if err != nil {
		SendError(w, "Error caught while hashing Password", http.StatusInternalServerError)
		return
	}

	hashPin, err := bcrypt.GenerateFromPassword([]byte(user.BankPin), bcrypt.DefaultCost) // Hash bank pin
	if err != nil {
		SendError(w, "Caught error trying to hash the pin", http.StatusInternalServerError)
		return
	}

	//Take the user's information from Go, insert it into the users table in MySQL, and save the user's data.
	//EXEC:"Execute this SQL command.(uSE MY DATATBASE CONNECTION AND RUN THIS)
	result, err := db.DB.Exec(`INSERT INTO users(first_name,middle_name,last_name,phone,email,country, bank_pin,password) 
	VALUES(?,?,?,?,?,?,?,?)`, //Empty space waiiting for value that will come in

		user.FirstName,
		user.MiddleName,
		user.LastName,
		user.Phone,
		user.Email,
		user.Country,
		string(hashPin),
		string(hashpassword))

	if err != nil {
		if strings.Contains(err.Error(), "Duplicate entry") {
			SendError(w, "An account with this email already exists", http.StatusInternalServerError)
			return

		}

		SendError(w, "Error Saving User", http.StatusInternalServerError)
		return
	}

	// Retrieve the ID automatically generated by the database for the newly inserted user.
	// The database creates this ID because the users table has an AUTO_INCREMENT primary key.
	// We need this ID to link the user to other records, such as creating their bank account.
	newID, err := result.LastInsertId() //
	if err != nil {
		SendError(w, "Error retrieving new user ID", http.StatusInternalServerError)
		return
	}

	token, err := auth.GenarateToken(int(newID)) // Generate jwt token for any registered user
	if err != nil {
		SendError(w, "Error Generating token", http.StatusInternalServerError)
		return
	}

	Accountno, err := auth.GenerateAccountNo() // Generate Account number
	if err != nil {
		SendError(w, "Error Genarating Account number", http.StatusInternalServerError)
		return
	}

	// NOTE: "user_id", "account_number", and "balance" must match the exact
	// column names in the database. Any misspelling here will cause an error,
	// and this kind of bug can keep you stuck for a long time trying to find it.

	// This line inserts a new row into the "accounts" table.

	// The three question marks (?, ?, ?) are placeholders — they mean
	// "a value will be filled in here later," and each one lines up with
	// a column in the order the columns were listed above.

	// IMPORTANT: The order you pass values in MUST match the order of the
	// columns you listed in the INSERT statement.
	// Example: (user_id, account_number, balance) → (newID, Accountno, 0.00)
	//
	// If the types don't match at all (e.g. you try to insert a string into
	// a column declared as INT), the database will reject it and throw an error.
	//
	// But if the types DO match (e.g. everything is an int), the database
	// won't complain — it will just insert the values in the wrong columns.
	// So account_number could end up holding what was meant to be the balance,
	// and balance could end up holding the account number. No error, just
	// silently wrong data — which is worse, because it fails quietly.

	_, err = db.DB.Exec(`INSERT INTO accounts(user_id, account_number, balance) VALUES(?,?,?)`,
		newID, Accountno, 0.00)

	if err != nil {
		if strings.Contains(err.Error(), "Duplicate entry") {
			SendError(w, "Please try Again", http.StatusInternalServerError)
			return
		}
		SendError(w, "Error creating account", http.StatusInternalServerError)
		return
	}

	// Send the JWT token to the user's browser as a cookie.
	// After a successful login or registration, the browser stores this cookie
	// and automatically sends it back with future requests. This allows the
	// server to recognize the user without asking them to log in again.
	//
	// Cookie settings:
	// - Name: The cookie's identifier ("auth_token").
	// - Value: The generated JWT token.
	// - HttpOnly: Prevents JavaScript from accessing the cookie for better security.
	// - Path: "/" makes the cookie available to the entire website.
	// - Secure: Set to false for local development. Change to true in production
	//   so the cookie is only sent over HTTPS.
	// - SameSite: Helps protect against CSRF attacks by restricting when the
	//   browser sends the cookie to the server.
	// - Expires: The cookie becomes invalid after 24 hours.

	http.SetCookie(w, &http.Cookie{
		Name:     "auth_token",
		Value:    token,
		HttpOnly: true,
		Path:     "/",
		Secure:   false,
		SameSite: http.SameSiteLaxMode,
		Expires:  time.Now().Add(24 * time.Hour),
	})

	// Prepare the response that will be sent back to the frontend.
	// It includes a success message and the newly created user's details,
	// such as their ID, formatted name, email, and generated account number.
	resp := models.RegisterResponse{
		Message: "Registeration Succeessful",
		User: models.UserInfo{
			ID:        int(newID),
			FirstName: strings.Title(strings.ToLower(user.FirstName)),
			LastName:  strings.Title(strings.ToLower(user.LastName)),
			Email:     user.Email,
			AccountNo: Accountno,
		},
	}
	// Tell the client that the response being sent is in JSON format.
	w.Header().Set("Content-Type", "application/json")

	// Convert the Go response struct into JSON and send it to the client.
	json.NewEncoder(w).Encode(resp)

}
